#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 25 10:45:45 2019

@author: bikash
"""

STOP_CODONS = ['TAG', 'TAA', 'TGA']

AA_TO_CODON = { 'A' : ['GCT', 'GCC', 'GCA', 'GCG'], 
             #'stop' : ['TAA', 'TGA', 'TAG'], 
             'C' : ['TGT', 'TGC'], 
             'D' : [ 'GAT', 'GAC'], 
             'E' : ['GAA','GAG'], 
             'F' : ['TTT', 'TTC'], 
             'G' : ['GGT', 'GGC', 'GGA', 'GGG'], 
             'H' : ['CAT', 'CAC'], 
             'I' : ['ATT', 'ATC', 'ATA'], 
             'K' : ['AAG', 'AAA'], 
             'L' : ['TTA', 'TTG', 'CTT', 'CTC', 'CTG', 'CTA'], 
             'M' : ['ATG'], 
             'N' : ['AAT', 'AAC'], 
             'P' : ['CCT', 'CCC', 'CCA', 'CCG'], 
             'Q' : ['CAA', 'CAG'], 
             'R' : ['CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'], 
             'S' : ['TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC'], 
             'T' : ['ACT', 'ACC', 'ACA', 'ACG'], 
             'V' : ['GTT', 'GTC', 'GTA', 'GTG'], 
             'W' : ['TGG'], 
             'Y' : ['TAT', 'TAC'] }


CODON_TO_AA = { 'TTT' : 'F', 
             'TCT' : 'S', 
             'TAT' : 'Y', 
             'TGT' : 'C', 
             'TTC' : 'F', 
             'TCC' : 'S', 
             'TAC' : 'Y', 
             'TGC' : 'C', 
             'TTA' : 'L', 
             'TCA' : 'S', 
             'TAA' : '*', 
             'TGA' : '*', 
             'TTG' : 'L', 
             'TCG' : 'S', 
             'TAG' : '*', 
             'TGG' : 'W', 
             'CTT' : 'L', 
             'CCT' : 'P', 
             'CAT' : 'H', 
             'CGT' : 'R', 
             'CTC' : 'L', 
             'CCC' : 'P', 
             'CAC' : 'H', 
             'CGC' : 'R', 
             'CTA' : 'L', 
             'CCA' : 'P', 
             'CAA' : 'Q', 
             'CGA' : 'R', 
             'CTG' : 'L', 
             'CCG' : 'P', 
             'CAG' : 'Q', 
             'CGG' : 'R', 
             'ATT' : 'I', 
             'ACT' : 'T', 
             'AAT' : 'N', 
             'AGT' : 'S', 
             'ATC' : 'I', 
             'ACC' : 'T', 
             'AAC' : 'N', 
             'AGC' : 'S', 
             'ATA' : 'I', 
             'ACA' : 'T', 
             'AAA' : 'K', 
             'AGA' : 'R', 
             'ATG' : 'M', 
             'ACG' : 'T', 
             'AAG' : 'K', 
             'AGG' : 'R', 
             'GTT' : 'V', 
             'GCT' : 'A', 
             'GAT' : 'D', 
             'GGT' : 'G', 
             'GTC' : 'V', 
             'GCC' : 'A', 
             'GAC' : 'D', 
             'GGC' : 'G', 
             'GTA' : 'V', 
             'GCA' : 'A', 
             'GAA' : 'E', 
             'GGA' : 'G', 
             'GTG' : 'V', 
             'GCG' : 'A', 
             'GAG' : 'E', 
             'GGG' : 'G'}


cai_table = {'TTT': 0.296,
 'TTG': 0.02,
 'TTC': 1,
 'TTA': 0.2,
 'TGT': 0.5,
 'TGG': 1,
 'TGC': 1,
 'TGA': 1,
 'TCT': 1,
 'TCG': 0.017,
 'TCC': 0.744,
 'TCA': 0.077,
 'TAT': 0.239,
 'TAG': 1,
 'TAC': 1,
 'TAA': 1,
 'GTT': 1,
 'GTG': 0.221,
 'GTC': 0.066,
 'GTA': 0.495,
 'GGT': 1,
 'GGG': 0.019,
 'GGC': 0.724,
 'GGA': 0.01,
 'GCT': 1,
 'GCG': 0.424,
 'GCC': 0.122,
 'GCA': 0.586,
 'GAT': 0.434,
 'GAG': 0.259,
 'GAC': 1,
 'GAA': 1,
 'CTT': 0.042,
 'CTG': 1,
 'CTC': 0.037,
 'CTA': 0.007,
 'CGT': 1,
 'CGG': 0.004,
 'CGC': 0.356,
 'CGA': 0.004,
 'CCT': 0.07,
 'CCG': 1,
 'CCC': 0.012,
 'CCA': 0.135,
 'CAT': 0.291,
 'CAG': 1,
 'CAC': 1,
 'CAA': 0.124,
 'ATT': 0.185,
 'ATG': 1,
 'ATC': 1,
 'ATA': 0.003,
 'AGT': 0.085,
 'AGG': 0.002,
 'AGC': 0.41,
 'AGA': 0.004,
 'ACT': 0.965,
 'ACG': 0.099,
 'ACC': 1,
 'ACA': 0.076,
 'AAT': 0.051,
 'AAG': 0.253,
 'AAC': 1,
 'AAA': 1}
